services:
  - type: web
    name: webchat
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: GIPHY_API_KEY
        sync: false
      - key: TURN_URL
        sync: false
      - key: TURN_USERNAME
        sync: false
      - key: TURN_CREDENTIAL
        sync: false
